/* =========================================================
   ENGLISH COPY
   Arabic copy lives in index.html. Each key here matches a
   data-i18n="key" in index.html. Edit the text, keep the key.
   ========================================================= */
const EN = {
  "meta.title": "Mohamed Sherif — Brand Identity Designer & Branding Educator",
  "meta.desc": "Mohamed Sherif — brand identity designer and branding lecturer based in Cairo. I help companies build clear visual identities, and train designers through BRAND-SET and 1:1 mentoring.",
  "skip": "Skip to content",
  "close": "Close",
  "newtab": "(opens in a new tab)",
  "soon": "Link coming soon",

  "nav.label": "Navigation",
  "nav.top": "Back to top",
  "nav.about": "About",
  "nav.process": "For Companies",
  "nav.program": "Program",
  "nav.webinar": "Webinar",
  "nav.work": "Work",
  "nav.mentoring": "Mentoring",
  "nav.connect": "Connect",
  "nav.faq": "FAQ",

  "hero.lead": "I help companies build clear, consistent visual identities — and teach designers to design identity <em>beyond the logo.</em>",
  "cta.work": "Work With Me",
  "cta.learn": "Learn With Me",

  "about.lead": "Brand identity designer and branding lecturer based in Cairo. I work with companies and brands across Egypt and the Gulf on their visual identities — from the logo to the brand guidelines. Alongside that, I pass the experience on to designers through practical programs and 1:1 mentoring.",
  "clients.t": "Brands I've worked with",
  "about.photoAlt": "Mohamed Sherif — brand identity designer",
  "about.taught": "Taught",
  "about.f5": "students & designers",
  "about.since": "Since",
  "about.f1": "in design",
  "about.f2": "specialized in brand identity",
  "about.founder": "Founder",
  "about.f3": "identity studio",
  "about.partner": "Partner & MD",
  "about.f4": "design community & education",

  "do.lead": "Three tracks, one way of thinking: identity is a decision, not a look.",
  "do.a1.t": "Identities that work",
  "do.a1.p": "A complete visual identity designed around the business and its audience, working with the same clarity at every touchpoint.",
  "do.a1.l1": "Logo design",
  "do.a1.l2": "Visual identity system",
  "do.a1.l3": "Brand guidelines",
  "do.a2.t": "Learning by doing",
  "do.a2.p": "Practical programs built on real projects — from the brief to the final delivery files.",
  "do.a2.l1": "Courses",
  "do.a2.l2": "Workshops",
  "do.a2.l3": "Free webinars",
  "do.a3.t": "Guidance on your own work",
  "do.a3.p": "One-to-one, on your work: where you are now, and exactly what comes next.",
  "do.a3.l1": "Free intro session",
  "do.a3.l2": "1:1 mentoring",
  "do.a3.l3": "Portfolio review",

  "proc.lead": "For companies and brands that want a visual identity built on a real understanding of their business and audience — not on personal taste.",
  "proc.s1.t": "Get in touch",
  "proc.s1.p": "Send your project idea and a short note about your business, and I'll reply with the next step.",
  "proc.s2.t": "Understand the project",
  "proc.s2.p": "We sit together to understand your business, audience and goals, and write the project brief.",
  "proc.s3.t": "Quotation & plan",
  "proc.s3.p": "You receive a clear quotation with deliverables and timeline — before any design starts.",
  "proc.s4.t": "Design & delivery",
  "proc.s4.p": "From the first concepts to the full identity, final files and usage guide.",
  "proc.cta": "Start Your Project",

  "prog.desc": "A practical visual identity program that walks you through a full branding project, in the same order it happens in real work.",
  "prog.format": "Format",
  "prog.formatV": "lectures · a hands-on project in every lecture",
  "prog.enroll": "Enrollment",
  "prog.enrollV": "Always open · next cohort:",
  "prog.learn": "What you'll learn",
  "prog.o1": "Run an identity project through its four phases: Discovery, Thinking, Design, Production.",
  "prog.o2": "Handle clients, write a creative brief, and price with a clear quotation.",
  "prog.o3": "Turn research and keywords into a concept through mind-mapping.",
  "prog.o4": "Build a moodboard grounded in shape, color and type psychology.",
  "prog.o5": "Explore and validate the logo, then deliver a brand proposal and final files.",
  "prog.join": "Join",
  "prog.interest": "Not ready yet? Join the interest list",
  "prog.note": "Payment and course access are handled on Nzmly.",

  "fb.lead": "More than 860 students have learned with me. Here are some of their words, as they sent them.",
  "fb.alt": "Student feedback on BRAND-SET",
  "fb.hint": "Tap any message to enlarge it.",
  "fb.zoom": "Enlarged student feedback",

  "web.lead": "Start free. An open webinar before any commitment.",
  "web.next": "Next webinar",
  "web.desc": "Two hours to stop seeing branding as a logo and colors — and learn to judge any brand beyond its surface.",
  "web.date": "Date",
  "web.dur": "Duration",
  "web.durV": "2 hours · online",
  "web.price": "Price",
  "web.priceV": "Free",
  "web.cta": "See Dates & Register",
  "web.note": "All upcoming webinars are on my Luma page."

  "work.lead": "A small selection. The full archive lives on Behance.",
  "work.cta": "View Full Portfolio",

  "men.lead": "One-to-one sessions for designers who want to grow faster and with clarity. We review your work together, define your strengths and what needs work, and you leave every session with practical steps to apply right away to your projects and portfolio.",
  "men.s1.k": "Start here",
  "men.s1.t": "Free intro session",
  "men.s1.meta": "minutes · free · online",
  "men.s1.p": "We talk about your work, your current level and where you want to go — and agree on the right starting point for mentoring.",
  "men.s1.cta": "Book a Free Session",
  "men.s2.k": "Then",
  "men.s2.t": "1:1 Mentoring",
  "men.s2.meta": "90 minutes · online via Google Meet",
  "men.s2.p": "What you get from the sessions:",
  "men.b1": "An honest review of your work and portfolio",
  "men.b2": "A clear plan to level up your identity design",
  "men.b3": "Practical answers on clients, pricing and workflow",
  "men.b4": "Direct guidance on the projects you're working on now",
  "men.s2.cta": "Book a Mentoring Session",
  "men.s2.note": "Session choice, scheduling, payment and confirmation — all on Nzmly.",

  "faq.lead": "Questions I often get before any project or session starts.",
  "faq.q1": "How long does a visual identity project take?",
  "faq.a1": "Usually 4 to 6 working weeks, starting from the first payment and once all the project inputs are complete.",
  "faq.q2": "How does payment work?",
  "faq.a2": "50% upfront to start, and 50% before the final files are delivered. Full usage rights transfer on full payment.",
  "faq.q3": "How many revision rounds are included?",
  "faq.a3": "Two revision rounds per item in the quotation; any extra revisions are agreed in advance.",
  "faq.q4": "Do you work with companies outside Egypt?",
  "faq.a4": "Yes — I work with companies and brands across Egypt and the Gulf, and communication and delivery are fully online.",
  "faq.q5": "Who is BRAND-SET for?",
  "faq.a5": "Designers who want to learn to build a complete visual identity following the steps of real projects — from handling the client to final delivery.",
  "faq.q6": "How does a mentoring session work?",
  "faq.a6": "A one-to-one, 90-minute online session on Google Meet. Scheduling, payment and confirmation are all handled on Nzmly.",

  "con.lead": "Where I share the work, the thinking, and what happens behind the scenes.",

  "int.t": "Interest List",
  "int.p": "Register your interest and get the next cohort's details first. No payment commitment.",
  "int.ph": "The form will appear here once Tally is connected. Suggested fields:",
  "int.f1": "Name",
  "int.f2": "Email",
  "int.f3": "WhatsApp",
  "int.f4": "Experience level",
  "int.f5": "Program of interest"
};
