/* =========================================================
   ENGLISH COPY
   Arabic copy lives in index.html. Each key here matches a
   data-i18n="key" in index.html. Edit the text, keep the key.
   ========================================================= */
const EN = {
  "nav.identity": "Brand Identity",
  "svc.t4": "Free webinars",
  "svc.t3": "1:1 mentoring sessions",
  "svc.t2": "The visual identity course",
  "svc.t1": "Brand identity for companies",
  "prog.date": "Friday, 23 October 2026",
  "men.s1.note": "Booking is through Google Calendar; you'll receive the meeting link once it's confirmed.",
  "book.t": "Book Your Free Intro Session",
  "book.p": "30 minutes online via Google Meet. Pick the day and time that suit you, and you'll receive the meeting link once you book.",
  "nav.menu": "Menu",
  "nav.feedback": "Feedback",
  "nav.services": "Services",
  "nav.resume": "Resume",
  "about.big1": "I'm Mohamed Sherif, a brand identity designer and branding lecturer based in Cairo. I work with companies and brands across Egypt and the Gulf to build their visual identities — from the logo to the brand guidelines.",
  "about.big2": "Alongside that, I share what I've learned with designers through hands-on courses and one : one sessions.",
  "work.more": "View Project",
  "svc.1t": "Brand Identity",
  "svc.2t": "Visual Identity Course",
  "svc.2p": "A hands-on, six-lecture course where you build a complete identity, step by step, the way real projects run.",
  "svc.2l1": "From brief to final delivery",
  "svc.2l2": "A hands-on project in every lecture",
  "svc.2l3": "Enrollment open year-round",
  "svc.2cta": "Course Details",
  "svc.3t": "One : One Session",
  "svc.3p": "A 90-minute one-to-one session focused on your own work and projects — starting with a free intro call.",
  "svc.4t": "Free Webinars",
  "svc.4l3": "New dates on Luma",
  "svc.strip": "Didn't find what you're looking for?",
  "svc.stripCta": "Get in touch.",
  "res.lead": "I've been designing since 2016 and have specialized in visual identity since 2020 — it's the work I love and do best.",
  "res.r0": "A studio I founded to design visual identities for companies in Egypt and the Gulf.",
  "res.r1": "Leading the art direction of projects, from concept to delivery.",
  "res.r2": "Designing visual identities for brands, mostly for Gulf clients.",
  "res.r3": "Designing identities and print for brands across different sectors.",
  "res.r4": "Social media, advertising campaigns and print design.",
  "cta.email": "Email Me",

  "meta.title": "Mohamed Sherif — Brand Identity Designer & Branding Educator",
  "meta.desc": "Mohamed Sherif — brand identity designer and branding lecturer based in Cairo. I help companies build clear visual identities, and train designers through the BRAND-SET course and 1:1 mentoring.",
  "skip": "Skip to content",
  "close": "Close",
  "newtab": "(opens in a new tab)",
  "soon": "Link coming soon",

  "nav.label": "Navigation",
  "nav.top": "Back to top",
  "nav.about": "About",
  "nav.process": "For Companies",
  "nav.program": "Program",
  "nav.webinar": "Webinar",
  "nav.work": "Work",
  "nav.mentoring": "Mentoring",
  "nav.connect": "Contact",
  "nav.faq": "FAQ",

  "hero.lead": "I help companies build clear, consistent visual identities — and teach designers to design identity <em>beyond the logo.</em>",
  "cta.work": "Work With Me",
  "cta.learn": "Learn With Me",

  "about.lead": "Brand identity designer and branding lecturer based in Cairo. I work with companies and brands across Egypt and the Gulf on their visual identities — from the logo to the brand guidelines. Alongside that, I pass the experience on to designers through practical programs and 1:1 mentoring.",
  "clients.t": "Brands I've worked with",
  "about.photoAlt": "Mohamed Sherif — brand identity designer",
  "about.taught": "Taught",
  "about.f5": "students and designers taught",
  "about.since": "Since",
  "about.f1": "years of design experience",
  "about.f2": "clients and brands",
  "about.founder": "Founder",
  "about.f3": "Visual identity studio",
  "about.partner": "Partner & Managing Director",
  "about.f4": "Design community & education platform",

  "do.lead": "One service for companies, three ways to learn — and one idea behind them all: identity is a decision, not a look.",
  "do.a1.t": "Identities that work",
  "do.a1.p": "A complete visual identity shaped around your business and your audience, and just as clear at every touchpoint.",
  "do.a1.l1": "Logo design",
  "do.a1.l2": "Visual identity system",
  "do.a1.l3": "Brand guidelines",
  "do.a2.t": "Learning by doing",
  "do.a2.p": "Practical programs built on real projects — from the brief to the final delivery files.",
  "do.a2.l1": "Courses",
  "do.a2.l2": "Workshops",
  "do.a2.l3": "Free webinars",
  "do.a3.t": "Guidance on your own work",
  "do.a3.p": "One-to-one, on your work: where you are now, and exactly what comes next.",
  "do.a3.l1": "Free intro session",
  "do.a3.l2": "1:1 mentoring",
  "do.a3.l3": "Portfolio review",

  "proc.lead": "If you're looking for a visual identity built on a real understanding of your business and your audience, this is where we start.",
  "proc.s1.t": "Get in Touch",
  "proc.s1.p": "Share your project idea and a little about your business, and I'll get back to you with the next step.",
  "proc.s2.t": "Understand the Project",
  "proc.s2.p": "We get to know your business, audience and goals together, and write the project brief.",
  "proc.s3.t": "Quotation & Plan",
  "proc.s3.p": "You receive a clear quotation with deliverables and timeline — before any design work begins.",
  "proc.s4.t": "Design & Delivery",
  "proc.s4.p": "From first concepts to the complete identity, with final files and usage guidelines.",
  "proc.cta": "Start Your Project",

  "prog.desc": "A hands-on visual identity course that takes you step by step through a complete branding project — in the same order real projects follow.",
  "prog.format": "Format",
  "prog.formatV": "lectures · a hands-on project in every lecture",
  "prog.enroll": "Enrollment",
  "prog.enrollV": "Open year-round · Next cohort:",
  "prog.learn": "What you'll learn",
  "prog.o1": "Run an identity project through its four phases: Discovery, Thinking, Design and Production.",
  "prog.o2": "Work with clients professionally, write a creative brief, and price your work with a clear quotation.",
  "prog.o3": "Turn research and keywords into a design concept using mind-mapping.",
  "prog.o4": "Build a moodboard grounded in the psychology of shape, color and type.",
  "prog.o5": "Develop and test the logo, then present the brand proposal and deliver the final files.",
  "prog.join": "Enroll in",
  "prog.interest": "Not ready yet? Join the interest list",
  "prog.note": "Payment and course access are handled through Nzmly.",

  "fb.lead": "More than 850 students have learned with me. Here are some of their words, exactly as they sent them.",
  "fb.alt": "BRAND-SET student feedback",
  "fb.s1": "rated the instructor's knowledge and skills as “excellent”",
  "fb.s2": "rated his teaching and engagement as “excellent”",
  "fb.s3": "rated the overall training as “excellent”",
  "fb.src": "From a survey of 69 students after one BRAND-SET course cohort.",
  "fb.prev": "Previous",
  "fb.next": "Next",
  "fb.hint": "Swipe for more, and tap any image to enlarge it.",
  "fb.zoom": "Enlarged student feedback",

  "web.lead": "Start for free with an open webinar — no commitment.",
  "web.next": "Next webinar",
  "web.desc": "Two hours to look past the logo and colors — and understand what really gives a brand its value.",
  "web.date": "Date",
  "web.dur": "Duration",
  "web.durV": "2 hours · online",
  "web.price": "Price",
  "web.priceV": "Free",
  "web.cta": "See Dates & Register",
  "web.note": "All upcoming webinars are listed on my Luma page.",

  "work.lead": "A selection of identities designed for companies across different sectors. The full archive is on Behance.",
  "work.cta": "View Full Portfolio",

  "men.lead": "One-to-one sessions for designers who want to grow with more clarity and momentum. We review your work together, pinpoint your strengths and what to develop next, and you leave every session with practical steps you can apply straight away.",
  "men.s1.k": "Start here",
  "men.s1.t": "Free Intro Session",
  "men.s1.meta": "minutes · free · online",
  "men.s1.p": "We talk about your work, where you are now and where you want to go — and agree on the best place to start.",
  "men.s1.cta": "Book Your Free Session",
  "men.s2.k": "Then",
  "men.s2.t": "One : One Sessions",
  "men.s2.meta": "90 minutes · online via Google Meet",
  "men.s2.p": "What you'll get from the sessions:",
  "men.b1": "An honest, constructive review of your work and portfolio",
  "men.b2": "A clear plan to grow your identity design skills",
  "men.b3": "Practical answers on clients, pricing and workflow",
  "men.b4": "Direct guidance on the projects you're working on now",
  "men.s2.cta": "Book a Mentoring Session",
  "men.s2.note": "Session choice, scheduling, payment and confirmation are all handled through Nzmly.",

  "faq.lead": "Questions I'm often asked before a project or session begins.",
  "faq.q1": "How long does a visual identity project take?",
  "faq.a1": "Usually 4 to 6 working weeks, starting once the first payment is received and all project information is in place.",
  "faq.q2": "How does payment work?",
  "faq.a2": "50% upfront to begin, and 50% before the final files are delivered. Full usage rights transfer once payment is complete.",
  "faq.q3": "How many revision rounds are included?",
  "faq.a3": "Two rounds of revisions per item in the quotation; any additional revisions are agreed on in advance.",
  "faq.q4": "Do you work with companies outside Egypt?",
  "faq.a4": "Yes — I work with companies and brands across Egypt and the Gulf, with communication and delivery handled fully online.",
  "faq.q5": "Who is the BRAND-SET course for?",
  "faq.a5": "For designers who want to learn how to build a complete visual identity the way real projects run — from working with the client to final delivery.",
  "faq.q6": "How does a mentoring session work?",
  "faq.a6": "A one-to-one, 90-minute online session on Google Meet. Scheduling, payment and confirmation are all handled through Nzmly.",

  "con.lead": "Where I share the work, the thinking, and what happens behind the scenes.",

  "int.t": "Interest List",
  "int.p": "Register your interest and be the first to hear about the next cohort — no payment commitment.",
  "int.ph": "The form will appear here once Tally is connected. Suggested fields:",
  "int.f1": "Name",
  "int.f2": "Email",
  "int.f3": "WhatsApp",
  "int.f4": "Experience level",
  "int.f5": "Course of interest"
};
