/* =========================================================
   BRAND-SET page — ENGLISH COPY
   Arabic copy lives in brand-set/index.html. Same keys.
   ========================================================= */
const EN = {
  "meta.title": "BRAND-SET — The Visual Identity Course with Mohamed Sherif",
  "meta.desc": "BRAND-SET: a six-lecture online course where you build a complete visual identity the way real projects run — from client brief to final delivery files. Next cohort starts Friday, 23 October 2026. 20 seats only.",
  "skip": "Skip to content",
  "close": "Close",
  "newtab": "(opens in a new tab)",
  "soon": "Link coming soon",

  "nav.label": "Navigation",
  "nav.home": "Home",
  "nav.start": "Starts 23 Oct",

  "cta.register": "Register Now",
  "cta.curriculum": "See the Curriculum",

  "hero.promise": "Build a complete visual identity — <em>the way real projects run.</em>",
  "hero.lead": "A six-lecture online course with Mohamed Sherif: from the client brief to the brand proposal and final delivery files.",
  "fact.start.k": "Starts",
  "fact.start.v": "Friday, 23 October",
  "fact.format.k": "Format",
  "fact.format.v": "6 lectures × 3 hours",
  "fact.where.k": "Where",
  "fact.where.v": "Online + recordings",
  "fact.seats.k": "Seats",
  "fact.seats.v": "20 seats only",
  "price.cur": "EGP",
  "price.until": "· Launch price until Friday, 16 October",

  "prob.lead": "Many designers can draw a beautiful logo. But clients don't just need a logo — they need a complete identity built on an understanding of their business.",
  "prob.1t": "You deliver a logo, not an identity",
  "prob.1p": "The project ends at the logo: no considered colors, no graphic elements, no visual system that works at every touchpoint. The work looks smaller than it is — and it's harder to price.",
  "prob.2t": "You don't know how to run a project from start to finish",
  "prob.2p": "Where do you start with a client? What do you ask? How do the answers become a concept, the concept a logo, and the logo a brand proposal with delivery files? Without a clear method, every project starts from zero.",

  "out.lead": "Every lecture moves your final project one step forward, so you finish the course with two things:",
  "out.1t": "A complete identity project in your portfolio",
  "out.1p": "From brief to brand proposal: logo, colors, graphic elements, applications and final delivery files — a project you can show with confidence.",
  "out.2t": "A method you can use with any client",
  "out.2p": "Four clear phases you apply to every project — Discovery, Thinking, Design and Production — plus a way to work with clients and price your work with a clear quotation.",

  "cur.lead": "6 lectures over 3 weekends, 3 hours each — Fridays and Saturdays at 6:30 pm Cairo time.",
  "cur.1": "Core branding vocabulary, the seven logo types and when to choose each, and four tests every logo must pass: clarity, differentiation, concept and alignment.",
  "cur.1d": "Fri 23 Oct",
  "cur.2": "Working with different client types, writing the creative brief, preparing a quotation — and starting your final project from the brief.",
  "cur.2d": "Sat 24 Oct",
  "cur.3": "Turning the brief into keywords, mind-mapping and market research — and from there into a design concept with real meaning.",
  "cur.3d": "Fri 30 Oct",
  "cur.4": "The psychology of shape, color and type, and how to build a moodboard that sets the identity's visual direction.",
  "cur.4d": "Sat 31 Oct",
  "cur.5": "From style-scape to sketches and logo exploration techniques, then vectorizing, refining ratios and testing the logo before sign-off.",
  "cur.5d": "Fri 6 Nov",
  "cur.6": "Building graphic elements and the visual system, then preparing the brand proposal and final delivery files for the client.",
  "cur.6d": "Sat 7 Nov",

  "fit.lead": "There are only 20 seats, so make sure the course is right for you before you register.",
  "fit.yes": "It's for you if you",
  "fit.y1": "Have previous design experience and work in Illustrator and Photoshop",
  "fit.y2": "Want to move from designing a logo to building a complete visual identity",
  "fit.y3": "Freelance and want a clear method for clients and pricing",
  "fit.y4": "Want a strong identity project in your portfolio",
  "fit.no": "It's not for you if you",
  "fit.n1": "Are starting design from zero or haven't used design software yet",
  "fit.n2": "Are looking for ready-made templates or quick results without practice",
  "fit.n3": "Can't set aside time to work on your project between lectures",

  "inst.alt": "Mohamed Sherif",
  "inst.name": "Mohamed Sherif",
  "inst.p": "Brand identity designer and branding lecturer based in Cairo, designing since 2016. He has designed identities for companies and brands across Egypt and the Gulf, and teaches the same method he uses with his clients.",
  "inst.s1": "students and designers taught",
  "inst.s2": "rated the instructor's knowledge and skills as “excellent”*",
  "inst.s3": "clients and brands",
  "inst.src": "* From a survey of 69 students after one BRAND-SET cohort.",
  "inst.founder": "Founder",
  "inst.idntik": "Visual identity studio",
  "inst.partner": "Partner & Managing Director",
  "inst.branders": "Design community & education platform",

  "fb.lead": "Words from students of previous cohorts, exactly as they sent them.",
  "fb.alt": "BRAND-SET student feedback",
  "fb.prev": "Previous",
  "fb.next": "Next",
  "fb.hint": "Swipe for more, and tap any image to enlarge it.",
  "fb.zoom": "Enlarged student feedback",

  "det.lead": "Everything you need to know before you register.",
  "det.when.k": "Schedule",
  "det.when.v": "Fridays and Saturdays, 6:30 pm Cairo time — 3 weekends, 23 October to 7 November 2026",
  "det.len.k": "Length",
  "det.len.v": "6 lectures, 3 hours (180 minutes) each",
  "det.rec.k": "Online + recordings",
  "det.rec.v": "Lectures are online and every lecture is recorded — if you miss one, you can watch it afterwards",
  "det.tools.k": "Software",
  "det.cert.k": "Certificate",
  "det.cert.v": "A certificate of completion once you submit your final project",
  "det.be.k": "Your work, shown",
  "det.be.v": "The best student projects are featured on my Behance",
  "det.seats.k": "Seats",
  "det.seats.v": "20 seats only for this cohort",

  "pr.lead": "Your seat in the cohort starting Friday, 23 October 2026.",
  "pr.i1": "6 online lectures × 3 hours",
  "pr.i2": "Recordings of every lecture",
  "pr.i3": "A complete identity project for your portfolio",
  "pr.i4": "Certificate of completion after your final project",
  "pr.i5": "A chance to have your project featured on Behance",
  "pr.tag": "Launch price — this cohort only",
  "pr.instead": "instead of",
  "pr.until": "Until Friday, 16 October 2026",
  "pr.seats": "20 seats only",
  "pr.note": "Registration and payment are handled through Nzmly.",

  "faq.lead": "The questions I'm asked most before people register.",
  "faq.q1": "How much experience do I need?",
  "faq.a1": "The course is for designers with previous design experience who work in Illustrator and Photoshop. If you're starting design from zero, it's better to build your fundamentals first.",
  "faq.q2": "What if I miss a lecture?",
  "faq.a2": "Every lecture is recorded, so you can watch any lecture you missed and keep up with your project alongside the cohort.",
  "faq.q3": "How do I pay?",
  "faq.a3": "Registration and payment are online through Nzmly, via the “Register Now” button. Your seat is confirmed once payment is complete.",
  "faq.q4": "What software do I need?",
  "faq.a4": "Adobe Illustrator and Adobe Photoshop.",
  "faq.q5": "Is there a certificate?",
  "faq.a5": "Yes — a certificate of completion once you submit your final project. The best student projects are also featured on my Behance.",

  "fin.t": "Only 20 seats in this cohort.",
  "fin.p": "Start the identity project you'll be proud to show in your portfolio.",
  "fin.early": "— launch price until 16 October"
};
