/* mentoring — ENGLISH COPY. Arabic lives in index.html (same keys). */
const EN = {
  "skip": "Skip to content",
  "close": "Close",
  "newtab": "(opens in a new tab)",
  "soon": "Link coming soon",
  "nav.label": "Navigation",
  "nav.home": "Home",
  "cta.email": "Email Me",
  "meta.title": "One : One Session — 1:1 Mentoring with Mohamed Sherif",
  "meta.desc": "A 90-minute one-to-one session on your own work with Mohamed Sherif, brand identity designer and branding lecturer. Start with a free intro call.",
  "nav.dur": "90 min",
  "cta.book": "Book Your Session",
  "cta.free": "Start with a free 30-min intro call",
  "cta.freeShort": "Book a Free Intro",
  "hero.promise": "A one-to-one session on your own work — <em>and you leave with clear next steps.</em>",
  "hero.lead": "For designers who want to grow with more clarity and momentum. We review your work together, pinpoint your strengths and what to develop next, and you leave with practical steps you can apply straight away.",
  "f.len.k": "Length",
  "f.len.v": "90 minutes",
  "f.where.k": "Where",
  "f.where.v": "Online · Google Meet",
  "f.book.k": "Booking",
  "f.book.v": "Through Nzmly",
  "f.start.k": "Start",
  "f.start.v": "Free 30-min intro call",
  "price.cur": "EGP",
  "price.per": "per session",
  "how.lead": "Three simple steps — and you can start for free.",
  "how.1t": "Free intro call",
  "how.1p": "30 minutes on Google Meet: we talk about your work, where you are now and where you want to go — and agree on the best place to start.",
  "how.2t": "Book your session",
  "how.2p": "Choose a time, pay and confirm your booking — all through Nzmly.",
  "how.3t": "90-minute session",
  "how.3p": "We review your work together, pinpoint your strengths and what to develop, and you leave with practical steps to apply right away.",
  "get.lead": "What you get from the session:",
  "get.1": "An honest, constructive review of your work and portfolio",
  "get.2": "A clear plan to grow your identity design skills",
  "get.3": "Practical answers on clients, pricing and workflow",
  "get.4": "Direct guidance on the projects you're working on now",
  "inst.alt": "Mohamed Sherif",
  "inst.name": "Mohamed Sherif",
  "inst.p": "Brand identity designer and branding lecturer based in Cairo, designing since 2016. He has designed identities for companies and brands across Egypt and the Gulf, and has taught more than 850 designers.",
  "inst.s1": "students and designers taught",
  "inst.s2": "rated the instructor's knowledge and skills as “excellent”*",
  "inst.s3": "clients and brands",
  "inst.src": "* From a survey of 69 students after one BRAND-SET cohort.",
  "faq.lead": "Questions I'm often asked before booking.",
  "faq.q1": "How do I book a session?",
  "faq.a1": "Use the “Book Your Session” button: choose a time, pay and confirm your booking — all through Nzmly.",
  "faq.q2": "Can I start with a free session?",
  "faq.a2": "Yes — a free 30-minute intro call on Google Meet, where we talk about your work and level and agree on the best place to start.",
  "faq.q3": "How does the session work?",
  "faq.a3": "A one-to-one, 90-minute online session on Google Meet, focused on your own work and questions.",
  "faq.q4": "I'm outside Egypt — can I book?",
  "faq.a4": "Yes. Sessions are online, and you can pay from any country with a Visa card through Nzmly; the price is in Egyptian pounds.",
  "faq.q5": "How is this different from the BRAND-SET course?",
  "faq.a5": "BRAND-SET is a six-lecture group course where you build a complete identity step by step. A One : One session is just you: your work, your questions, your next steps.",
  "faq.more": "See the BRAND-SET course",
  "fin.t": "Start with a free intro call — or book your session directly.",
  "fin.p": "90 minutes on your own work, with practical steps you can apply straight away.",
  "bar.t": "One : One Session · 1,500 EGP"
};
