/* brand-identity — ENGLISH COPY. Arabic lives in index.html (same keys). */
const EN = {
  "skip": "Skip to content",
  "close": "Close",
  "newtab": "(opens in a new tab)",
  "soon": "Link coming soon",
  "nav.label": "Navigation",
  "nav.home": "Home",
  "cta.email": "Email Me",
  "meta.title": "Brand Identity Design for Companies — Mohamed Sherif",
  "meta.desc": "Visual identities for companies and brands across Egypt and the Gulf, built on a real understanding of the business and its audience — from the logo to the brand guidelines.",
  "nav.for": "For Companies",
  "cta.start": "Start Your Project",
  "cta.work": "See the Work",
  "hero.promise": "A visual identity that expresses your business — <em>and works at every touchpoint.</em>",
  "hero.lead": "I design visual identities for companies and brands across Egypt and the Gulf, built on a real understanding of the business and its audience — from the logo to the brand guidelines.",
  "f.time.k": "Timeline",
  "f.time.v": "Usually 4–6 working weeks",
  "f.pay.k": "Payment",
  "f.pay.v": "50% upfront · 50% before delivery",
  "f.rev.k": "Revisions",
  "f.rev.v": "Two rounds per item",
  "f.where.k": "Where",
  "f.where.v": "Online — Egypt & the Gulf",
  "t.note": "You receive a clear quotation with deliverables and timeline — before any design work begins.",
  "get.lead": "Not just a logo: a complete identity your team can use with confidence.",
  "get.1t": "Logo Design",
  "get.1p": "A logo built on a clear idea drawn from your business, tested before sign-off so it works at every size and use.",
  "get.2t": "Visual Identity System",
  "get.2p": "The colors, typography and graphic elements that make everything you publish look like the same brand.",
  "get.3t": "Brand Guidelines",
  "get.3p": "A guide that shows your team — and anyone you work with — how to use the identity correctly.",
  "get.files": "Final delivery files:",
  "proc.lead": "A clear process from the first message to the final files — so you always know where the project stands.",
  "proc.s1.t": "Get in Touch",
  "proc.s1.p": "Share your project idea and a little about your business, and I'll get back to you with the next step.",
  "proc.s2.t": "Understand the Project",
  "proc.s2.p": "We get to know your business, audience and goals together, and write the project brief.",
  "proc.s3.t": "Quotation & Plan",
  "proc.s3.p": "You receive a clear quotation with deliverables and timeline — before any design work begins.",
  "proc.s4.t": "Design & Delivery",
  "proc.s4.p": "From first concepts to the complete identity, with final files and usage guidelines.",
  "work.lead": "A selection of identities designed for companies across different sectors.",
  "work.cta": "View Full Portfolio",
  "clients.t": "Brands I've worked with",
  "faq.lead": "Questions I'm often asked before a project begins.",
  "faq.q1": "How long does a visual identity project take?",
  "faq.a1": "Usually 4 to 6 working weeks, starting once the first payment is received and all project information is in place.",
  "faq.q2": "How does payment work?",
  "faq.a2": "50% upfront to begin, and 50% before the final files are delivered. Full usage rights transfer once payment is complete.",
  "faq.q3": "How many revision rounds are included?",
  "faq.a3": "Two rounds of revisions per item in the quotation; any additional revisions are agreed on in advance.",
  "faq.q4": "Do you work with companies outside Egypt?",
  "faq.a4": "Yes — I work with companies and brands across Egypt and the Gulf, with communication and delivery handled fully online.",
  "fin.t": "Ready to build your brand's identity?",
  "fin.p": "Share your project idea and a little about your business, and I'll get back to you with the next step.",
  "bar.t": "Brand Identity for Companies"
};
